_wandb:
    value:
        cli_version: 0.22.2
        e:
            cs6qqbraehpbrjv6ef1rtbec485q1n96:
                codePath: train_reconstruction.py
                codePathLocal: train_reconstruction.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1965728006144"
                        used: "43638411264"
                email: ytytjkh@gmail.com
                executable: /home/ljsong7/.conda/envs/rc/bin/python3.10
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-19e5f36e-78c0-9187-ce40-4e2cd0b11f1a
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f7bab865-0754-eca3-336a-da0dc9af2a9b
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-909d66cf-8d2e-3d20-bba3-8bc44645d91f
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-904637b1-cffd-850e-eb99-d308163bb123
                host: imil0
                memory:
                    total: "201361592320"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /mnt/home/ljsong7/recon_cu/reconstruction_curiousity/train_reconstruction.py
                python: CPython 3.10.12
                root: /mnt/home/ljsong7/recon_cu/reconstruction_curiousity
                startedAt: "2025-11-18T12:54:00.230901Z"
                writerId: cs6qqbraehpbrjv6ef1rtbec485q1n96
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 16
                - 61
                - 62
            "4": 3.10.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
early_stop:
    value: 20
eval_every:
    value: 1000
eval_step:
    value: 20
log_interval:
    value: 100
params:
    value:
        batch_size: 16
        dataset:
            data_dir: ../datas/ovc
        decay_lr: true
        epochs: 200
        grad_clip: 1
        model:
            gpt_config:
                batch_size: 16
                bias: true
                dropout: 0
                frame_length: 400
                n_embd: 950
                n_head: 10
                n_layer: 4
            in_features: 950
            out_units: 2200
        num_worker: 8
        optimizer:
            betas:
                - 0.9
                - 0.95
            eps: 1e-06
            lr: 0.0006
            weight_decay: 0.1
        scheduler:
            lr_decay_iters: 200000
            min_lr: 3e-05
            warmup_iters: 5000
            wm_learning_rate: 0.0006
path:
    value:
        ckpt_path: ./out/ovc_recon/best_model.pt
        data_dir: ../datas/ovc
        out_dir: ./out/ovc_recon
save_interval:
    value: 10
wandb:
    value:
        entity: junesong
        project: ovc_recon
