_wandb:
    value:
        cli_version: 0.22.2
        e:
            1ltb6outpbpx5dnpkffnc55ayav0jplc:
                args:
                    - --env
                    - ovc_paper
                    - --agent_num
                    - "11"
                codePath: train_partner_with_collect_ovc.py
                codePathLocal: train_partner_with_collect_ovc.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1965728006144"
                        used: "43708678144"
                email: ytytjkh@gmail.com
                executable: /home/ljsong7/.conda/envs/rc/bin/python
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-19e5f36e-78c0-9187-ce40-4e2cd0b11f1a
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-f7bab865-0754-eca3-336a-da0dc9af2a9b
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-909d66cf-8d2e-3d20-bba3-8bc44645d91f
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-904637b1-cffd-850e-eb99-d308163bb123
                host: imil0
                memory:
                    total: "201361592320"
                os: Linux-6.8.0-79-generic-x86_64-with-glibc2.39
                program: /mnt/home/ljsong7/recon_cu/reconstruction_curiousity/train_partner_with_collect_ovc.py
                python: CPython 3.10.12
                root: /mnt/home/ljsong7/recon_cu/reconstruction_curiousity
                startedAt: "2025-11-30T12:01:27.707306Z"
                writerId: 1ltb6outpbpx5dnpkffnc55ayav0jplc
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
log_interval:
    value: 1
params:
    value:
        algorithm:
            action_dim: 6
            latent_dim: 400
            lstm_dim: 256
        base_seed: 100000
        batch_size: 24
        loss:
            entropy_weight: 0.02
            gamma: 0.99
            lambda_: 0.95
        max_episode_length: 400
        max_grad_norm: 1
        num_iterations: 30000
        optimizer:
            betas:
                - 0.99
                - 0.99
            eps: 1e-06
            lr: 0.0001
            weight_decay: 0.1
        save_interval: 200
path:
    value:
        ckpt_path: null
        out_dir: ./out/ovc_paper
        save_dir: null
wandb:
    value:
        entity: junesong
        project: ovc_paper
